config/routes.rb
Rails.application.routes.draw do
  resources :parties

  root to: "parties#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/party.rb
class Party < ApplicationRecord
  validates :title, :embeded_link, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: %i[show edit update destroy]
  after_action :add_new_view, only: :show
  after_action :update_embeded_link, only: %i[create update]

  def index
    @parties = Party.all
  end

  def show; end

  def new
    @party = Party.new
  end

  def edit; end

  def create
    @party = Party.new(party_params)

    respond_to do |format|
      if @party.save
        format.html { redirect_to party_url(@party), notice: "Party was successfully created." }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to party_url(@party), notice: "Party was successfully updated." }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @party.destroy

    respond_to do |format|
      format.html { redirect_to parties_url, notice: "Party was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_party
    @party = Party.find(params[:id])
  end

  def party_params
    params.require(:party).permit(:title, :embeded_link)
  end

  def add_new_view
    @party.views += 1
    @party.save
  end

  def update_embeded_link
    @party.embeded_link = @party.embeded_link.gsub("watch?v=", "embed/").split("&")[0]
    @party.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoParty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8 mt-5">
          <% if notice %>
            <p style="color: green"><%= notice %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/parties/_form.html.erb
<%= form_with(model: party) do |form| %>
  <% if party.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(party.errors.count, "error") %> prohibited this party from being saved:</h2>

      <ul>
        <% party.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating mb-3">
    <%= form.text_field :title, class: "form-control", id: "floatingInput", placeholder: "Nome da sala" %>
    <%= form.label "Nome da sala", style: "display: block", for:"floatingInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :embeded_link, class: "form-control", id: "floatingInput", placeholder: "Aqui vai o link do video" %>
    <%= form.label "Link do video", style: "display: block", for: "floatingInput" %>
  </div>

  <div class="text-end">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/parties/_party.html.erb
<div class="mb-5 mt-5" id="<%= dom_id party %>">
  <h3 class="mb-5 text-center"><%= party.title %></h5>
  <div class="m-2">
    <iframe width="100%" height="600" src="<%= party.embeded_link %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    <div class="row">
      <div class="col-md-4 text-center">
        <p>Visualizações</p>
        <p><%= party.views %></p>
      </div>
    </div>
  </div>
</div>

app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render "form", party: @party %>

<br>

<div>
  <%= link_to "Visualize a sala", @party %> |
  <%= link_to "Voltar a lista de salas", parties_path %>
</div>

app/views/parties/index.html.erb
<h1 class="text-center">Salas de videos</h1>

<div id="parties">
  <table class="table table-striped">
    <thead>
      <tr class="text-center">
        <th scope="col">ID</th>
        <th scope="col">Titulo</th>
        <th scope="col">Visualizações</th>
        <th scope="col">Likes</th>
        <th scope="col">Dislikes</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @parties.each do |party| %>
        <tr class="text-center">
          <td><%= party.id %></td>
          <td><%= party.title %></td>
          <td><%= party.views %></td>
          <td><%= party.like %></td>
          <td><%= party.dislike %></td>
          <td>
            <div class="d-flex justify-content-around">
              <div>
                <%= link_to party_path(party), class: "btn btn-outline-success" do %>
                  <span>
                    <i class="bi bi-search"></i>
                  </span>
                <%end%>
              </div>
              <div>
                <%= link_to edit_party_path(party), class: "btn btn-outline-primary" do %>
                  <span>
                    <i class="bi bi-pencil"></i>
                  </span>
                <%end%>
              </div>
              <div>
                <%= button_to party, method: :delete, class: "btn btn-outline-danger", data: {confirm: "Are you sure?"} do %>
                  <span>
                    <i class="bi bi-trash"></i>
                  </span>
                <%end%>
              </div>
          </td>
        </tr>
      <% end %>
    </tbody>
</div>

<div class="m-4 text-end">
  <%= link_to "Nova sala", new_party_path, class: "btn btn-primary text-end" %>
</div>

app/views/parties/new.html.erb
<div class="mb-5">
  <%= link_to "Voltar a lista de salas", parties_path %>
</div>

<h1>Criar nova sala</h1>

<%= render "form", party: @party %>

<br>

app/views/parties/show.html.erb
<div>
  <%= link_to "Voltar a lista de salas", parties_path %>
</div>

<%= render @party %>